version: 2
project_name: concierge
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: concierge
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/canonical/concierge/cmd.version={{ .Version }} -X github.com/canonical/concierge/cmd.commit={{ .Commit }}
archives:
  - ids:
      - default
    files:
      - "LICENSE*"
      - "README*"

snapcrafts:
  - name: concierge
    publish: true
    license: Apache-2.0
    base: core24
    confinement: classic
    grade: stable
    summary: A utility for configuring dev/test machines for charm development
    description: |
      concierge is an opinionated utility for provisioning charm development and testing machines.

      Its role is to ensure that a given machine has the relevant "craft" tools and providers
      installed, then bootstrap a Juju controller onto each of the providers. Additionally, it can
      install selected tools from the [snap store](https://snapcraft.io) or the Ubuntu archive.

      Configuration is by flags/environment variables, or by configuration file. The configuration file
      must be in the current working directory and named 'concierge.yaml', or the path specified using
      the '-c' flag.

      There are 3 presets available by default: 'machine', 'k8s' and 'dev'.

      Some aspects of presets and config files can be overridden using flags such as '--juju-channel'.
      Each of the override flags has an environment variable equivalent, such as
      'CONCIERGE_JUJU_CHANNEL'.

      More information at https://github.com/canonical/concierge.
    extra_files:
      - source: .github/concierge.png
        destination: concierge.png
        mode: 0644
    apps:
      concierge:
        environment:
          SNAPCRAFT_BUILD_INFO: 1

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
release:
  prerelease: auto
  # Defaults to empty.
  footer: |
    ## Thanks!

    That's all the changes for {{ .Tag }}!
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^ci:"
