name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "!**"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/_checks.yaml
    permissions:
      contents: read

  test:
    uses: ./.github/workflows/_tests.yaml
    with:
      arch: amd64
      runner: ubuntu-24.04
